fix: attempt to fix autoupdate

diff --git a/.github/workflows/autoupdate_python_versions.yml b/.github/workflows/autoupdate_python_versions.yml
--- a/.github/workflows/autoupdate_python_versions.yml
+++ b/.github/workflows/autoupdate_python_versions.yml
@@ -7,7 +7,7 @@ on:
   push:
     paths:
       - 'scripts/**'
-
+      - '.github/workflows/autoupdate_python_versions.yml'
 
 env:
   MAIN_PYTHON_VERSION: '3.12'
@@ -45,13 +45,16 @@ jobs:
           echo "User configured as $(git config user.name) <$(git config user.email)>"
 
           # Check if there are any changes
-          diff_code=$(git diff --exit-code)
+          git diff --exit-code 2>/dev/null
+
+          # Store the exit code
+          diff_code=$?
           echo "Diff code: $diff_code"
 
           # If there are changes, verify whether the branch 'feat/update-python-version' exists
           # If it does, switch to it, rebase it on top of the main branch, and push the changes
           # If it doesn't, create the branch, commit the changes, and push the branch
-          if [ -n "$diff_code" ]; then
+          if [ $diff_code -ne 0 ]; then
             if git show-ref --verify --quiet refs/heads/feat/update-python-version; then
               echo "Branch 'feat/update-python-version' exists. Switching to it, rebasing on top of the main branch, and pushing the changes."
               git checkout feat/update-python-version
@@ -70,7 +73,7 @@ jobs:
           fi
 
           # If there are changes, create a pull request
-          if [ -n "$diff_code" ]; then
+          if [ $diff_code -ne 0 ]; then
             echo "Creating a pull request..."
             gh pr create --title "chore: update Python versions" --body "This PR updates the Python versions in the CI configuration files." --base main --head feat/update-python-version
           fi
